apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
spec:
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: dnurmuradov/pal-tracker:v5
          resources:
            limits:
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sleep", "10" ]
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: pal-tracker